name: Test Suite
on:
  push:
    branches: [main, feat/comprehensive-testing-suite]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run test:coverage  # Run tests with coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
      - run: npm run lint
      - run: npm run typecheck || true  # Allow to fail initially
      
      # Run benchmarks as part of CI (without performance regression checks)
      - name: Run benchmarks (smoke test)
        run: npm run benchmark -- --run tests/benchmarks/sample.bench.ts
        continue-on-error: true